name: frontend
description: A decentralized app for samrt booking system
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dynamic_color: ^1.6.6
  easy_dynamic_theme: ^2.3.1
  easy_localization: ^3.0.2
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  firebase_database: ^10.2.4
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  go_router: ^9.1.0
  json_annotation: ^4.8.1
  logger: ^1.4.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  walletconnect_flutter_v2: ^2.0.14
  web3dart: ^2.7.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  web3dart_builders: ^0.0.7

flutter:
  uses-material-design: true
  assets:
    - assets/translations/